### ISSUE TITLE
R-5.10 - Description

### ISSUE THREAD

**Issue by naesheim** [radon-h2020/functionHub-client#4]
| ID | R-T5.10|
| --- | --- |
| Section | WP5: Toolchain|
| Type | USABILITY |
| User Story | As a user I want more information about the Function |
| Requirement | Added a 'description' field in the config.ini file |
| Extended Description | As you upload a function, relevant information about the Function must be passed along |
| Affected Tools | FunctionHub |
| Means of Verification | Unit test |
| Dependency | N/A |

**Comment by gcasale** [comment]
Approved
