### ISSUE TITLE
R-T5.1 - Deploy token

### ISSUE THREAD

**Issue by naesheim** [radon-h2020/functionHub-client#5]
| ID | R-T5.1-8 |
| --- | --- |
| Section | WP5: Toolchain|
| Type | USABILITY |
| User Story | As a user I need to prove my ownership of a specific repository. |
| Requirement | You need a token to upload a function. |
| Extended Description | When you create a user you will be provided by a token. This token is used whenever you are uploading content to FunctionHub. Using the client, you have to set the token as an environment variable or pass it as a parameter in order to upload the function to your repository. |
| Affected Tools | FunctionHub |
| Means of Verification | Unit test |
| Dependency | N/A |

**Comment by gcasale** [comment]
Approved
