### ISSUE TITLE
R-5.17 - Private repositories

### ISSUE THREAD

**Issue by naesheim** [radon-h2020/functionHub-client#7]
| ID | R-T5.17 |
| --- | --- |
| Section | WP5: Toolchain|
| Type | USABILITY |
| User Story | As a user I want to create private repositories for private Functions |
| Requirement | Only logged in user can view private repositories |
| Extended Description | When creating a repository, you can decide if the repo is private or public. |
| Affected Tools | FunctionHub |
| Means of Verification | Unit test |
| Dependency | N/A |

**Comment by gcasale** [comment]
Approved

**Comment by AlexSpart** [comment]
This requirement is met. The user can decide if the repository that is creating in FunctionHub is public or private and only him can have access to the content of his private repossitories.

**Comment by gcasale** [comment]
OK to close
