### ISSUE TITLE
R-T5.22 - Deploy FaaS through URL

### ISSUE THREAD

**Issue by naesheim** [radon-h2020/functionHub-client#9]
| ID | R-T5.1-8 |
| --- | --- |
| Section | WP5: Toolchain|
| Type | USABILITY |
| User Story | As a user I want to deploy a Function as a part of an Application based on the URL available at cloudstash.io |
| Requirement | Deploy FaaS based on URL  |
| Extended Description | URL as a source for deployment. Similar to how you would use a local zip file for uploading today.  |
| Affected Tools | FunctionHub |
| Means of Verification | Unit test |
| Dependency | N/A |

**Comment by naesheim** [comment]
Relates to GMT: https://github.com/radon-h2020/radon-gmt/issues/27

**Comment by gcasale** [comment]
Approved

**Comment by AlexSpart** [comment]
This requirement is met. With the latest version of GMT I have successfully deployed a function as a part of an Application based on the URL.
*URL leads to an artifact or function source code that is offered publicly/privately in FunctionHub.

**Comment by naesheim** [comment]
Validated in D6.3

**Comment by gcasale** [comment]
Noted
